config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :places do
    resources :reviews
  end

  root "places#index"

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/place.rb
class Place < ActiveRecord::Base

	has_many :reviews 

	validates :name, presence: true, length: { minimum: 5 }
	validates :address, presence: true, length: { minimum: 5 }

	# these lines are for the geocoder gem to work
	# what's the field that we want to geocode based on 
	geocoded_by :address
	# when do we want to do it? .. after the top two things have happened, e.g. after we've validated
	after_validation :geocode

end

app/models/review.rb
class Review < ActiveRecord::Base

	belongs_to :place

	validates :body, presence: true
	validates :rating, inclusion: { in: 0..5 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

	def index

		# to get all places to show
		# @places = Place.all

		# to only get places near London
		# @places = Place.near("London")

		# to get places near the specified search if one has been done
		if params[:search].present?  
			@places = Place.near(params[:search] + ", UK", 100).page(params[:page]).per(3) 
			# addition in text narrows the search to UK, 100 after comma increases search area
			# page bit is limiting results to 3 places per page
		else 
			@places = Place.near("London").page(params[:page]).per(3) 
		end


	end

	def show
		@place = Place.find(params[:id])
	end

	def new

		@place = Place.new

	end

	def create
		@place = Place.new(place_params)

		if @place.save 

			flash[:success] = "Thanks for adding somewhere new"

			redirect_to root_path

		else 

			# show the new view again when save fails because of uniqueness validation
			render "new"

		end	

	end

	def place_params

		params.require(:place).permit(:name, :address, :longitude, :latitude) 

	end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	def new
		@place = Place.find(params[:place_id])
		@review = @place.reviews.new
	end

	def create
		@place = Place.find(params[:place_id])
		@review = @place.reviews.new(review_params)

		if @review.save

			flash[:success] = "Thanks for reviewing this place"

			# take me back to the homepage after saving
			redirect_to root_path

		else

			render "new"

		end

	end

	def review_params
		params.require(:review).permit(:body, :rating) 
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Burgersandbeer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>

<%= yield %>

</body>
</html>

app/views/places/index.html.erb
<section id="info">

	<header>
 		<h1><a href="#">Burgers and Beer</a></h1>
		<h2>London's best</h2>
  	</header>

  	<!-- This form sends the info specified to the URL.... -->
  	<form>
  		<input type="text" name="search" placeholder="Search">
  	</form>

	<ul>

		<% @places.each do |place| %>
			<li data-lat="<%= place.latitude %>" data-lng="<%= place.longitude %>">
				<h3><%= link_to place.name, place_path(place) %></h3>
				<p><%= place.address %></p>
				<% if params[:search].present? %>
					<p> 
						<%= place.distance_to(params[:search]).round(2) %> 
						<!-- find the distance from the searched place and rounds the distance to 2dp -->
						km away 
					</p>
				<% end %>
			</li>
		<% end %>

  </ul>

  <%= paginate @places %>

</section>

<section id="map"></section>

<%= link_to "Add a new place", new_place_path, class: "button" %>

app/views/places/new.html.erb
<h1>Add a New Place</h1>

<%= simple_form_for @place do |form| %>

	<%= form.input :name %>
	<%= form.input :address %>

	<%= form.button :submit %>

<% end %>

app/views/places/show.html.erb
<h2><%= @place.name %> </h2>

<p><%= @place.address %> <p>

	<% @place.reviews.each do |review| %>
<div class = "review">
	<%= simple_format review.body %>
	<!-- time helper -->
	<p><%= time_ago_in_words review.created_at %> ago </p>
</div>
<% end %>
<p>
	<!-- specifiying that this new comment is related to the story you're on -->
	<%= link_to "Add a review", new_place_review_path(@place) %> 
</p>

<%= link_to "Take me home", root_path %>

app/views/reviews/new.html.erb
<h2> Review <%= @place.name %> </h2>

<%= simple_form_for [@place, @review] do |form| %>

	<%= form.input :body, label: "Your review" %>
	<%= form.input :rating %>

	<%= form.button :submit, "Submit" %>

<% end %>